/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Authors: typeof import('./components/Authors.vue')['default']
    Books: typeof import('./views/Books.vue')['default']
    Content: typeof import('./components/Content.vue')['default']
    copy: typeof import('./components/EditAuthorModal copy.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DefaultDataTable: typeof import('./components/DefaultDataTable.vue')['default']
    EditAuthorModal: typeof import('./components/EditAuthorModal.vue')['default']
    EditBookModal: typeof import('./components/EditBookModal.vue')['default']
    EditSubjectModal: typeof import('./components/EditSubjectModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NewAuthorModal: typeof import('./components/NewAuthorModal.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Report: typeof import('./components/Report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebarmenu: typeof import('./components/Sidebarmenu.vue')['default']
    SnackbarNotification: typeof import('./components/SnackbarNotification.vue')['default']
    Subjects: typeof import('./components/Subjects.vue')['default']
  }
}
