/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultDataTable: typeof import('./components/DefaultDataTable.vue')['default']
    EditAuthorModal: typeof import('./components/EditAuthorModal.vue')['default']
    EditBookModal: typeof import('./components/EditBookModal.vue')['default']
    EditSubjectModal: typeof import('./components/EditSubjectModal.vue')['default']
    Report: typeof import('./components/Report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebarmenu: typeof import('./components/Sidebarmenu.vue')['default']
  }
}
